In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [6]:
print(a)

[1 2 3]


In [14]:
b = range(1,31)
print(b)

range(1, 31)


In [19]:
a = np.array(b).reshape(6,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [33]:
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])